### PR TITLE
feat(int-713): Adding option to log in the CLI with token (Enabling the possibility to login with SSO)

### PR DESCRIPTION
**Pull request by ademarCardoso**
## Pull request type

Jira Link: [INT-713](https://storyblok.atlassian.net/browse/INT-713)

- [x] Feature
- [x] Refactoring (no functional changes, no api changes)

## How to test this PR

Now you can use your token created in the user settings area, and you t login the CLI, like the video bellow, and the login with password still working normally. 

https://user-images.githubusercontent.com/40925579/218489411-c066890c-7e98-4447-958a-f5a397e30457.mov

## What is the new behavior?

- Now it's possible to use the CLI with SSO users login with the access_token
- The docs about login command is updated

## Other information

[INT-713]: https://storyblok.atlassian.net/browse/INT-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by thiagosaife — APPROVED** [review]

**Comment by frank7huysen** [comment]
@ademarCardoso What do you think of adding a --token arg so that it's possible to use it in a pipeline as well?

```
storyblok login --token x12adsa
```

**Comment by ademarCardoso** [comment]
> @ademarCardoso What do you think of adding a --token arg so that it's possible to use it in a pipeline as well?
> 
> ```
> storyblok login --token x12adsa
> ```

Nice idea my friend, i will talk with the team about this thing 🚀

**Comment by ademarCardoso** [comment]
> @ademarCardoso What do you think of adding a --token arg so that it's possible to use it in a pipeline as well?
> 
> ```
> storyblok login --token x12adsa
> ```

I talked to my squad and we are not going to add this feature right now because we have several other priorities, but I left an open task for development for the next sprints.

Thanks in advance for the idea 😄

**Comment by ademarCardoso** [comment]
> @ademarCardoso What do you think of adding a --token arg so that it's possible to use it in a pipeline as well?
> 
> ```
> storyblok login --token x12adsa
> ```

I talked again to my team and we added this new feature in this PR https://github.com/storyblok/storyblok-cli/pull/35

**Pull request merged**
