### PR TITLE
`pull-components`: options to include datasource values

### PR DESCRIPTION
**Pull request by RKcode**
## Pull request type

Jira Link: [INT-](url)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

Use the option `--resolve-datasources`/`--rb`

## What is the new behavior?

- Fetch datasources & datasource_entries
- Map those to component options

## Other information

Solve this #48

### CODE REVIEW

**Comment by merisbahti** [comment]
what's the status of this?

**Comment by tomsansome** [comment]
Hey @ademarCardoso, are the team happy with this work and the possibility of it being merged? It's something that would really improve typing, thanks!

**Comment by ademarCardoso** [comment]
I will share this PR with the management and lets see what we can do here, thanks for tagging me @tomsansome 😄 

@RKcode Could you please check the conflicts ?

Many thanks guys 🚀

**Comment by alvarosabu** [comment]
Hi @RKcode thanks a lot for this PR, would you be so kind as to resolve the conflicts present? That way I can download your fork and test it. 

Thanks!

**Comment by RKcode** [comment]
Hey @alvarosabu !
Thx for the answer, sorry I totally forgot that I contributed here

I fixed the conflicts, should be good to test/review 👍

**Comment by TwoBee** [comment]
Is there any news about this? This might be able to solve an [issue](https://github.com/storyblok/storyblok-cli/issues/121) I just opened.

**Comment by RKcode** [comment]
Small 🆙 @alvarosabu @ademarCardoso 
Tell me if you guys need anything else from me on this topic. I'll try to be reactive if there are any changes required after the review 👍

**Comment by alvarosabu** [comment]
Hi, @RKcode thanks for opening this PR, I need to test it before we merge it, we also need to update the readme with the new option.

**Review by alvarosabu — APPROVED** [review]
I just tested it and works as expected. Thank you very much for the great PR @RKcode   

Screenshot 2024-10-15 at 10 08 30

**Pull request merged**
