### PR TITLE
feat: add region-helper functionality 

### PR DESCRIPTION
**Pull request by BibiSebi**
This PR adds the new @storyblok/region-helper functionality and replaces the old way of managing the regions. This way there will be a single source of truth, which is the region-helper which will be consumed by other libraries and therefore will provide an easier and more stable way of dealing with regions.

Summary of additions: 

- [x] replace old region functionality with region helper
- [x] workflow to check for region-helper version updates

## Pull request type

Jira Link: [EXT-2186](https://storyblok.atlassian.net/browse/EXT-2186)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR
This change is not supposed to modify any behavior but as `region` is widely used throughout the project, many commands can be impacted by it. So, as far as I have mapped here, the following commands are the ones that should be validated:

- Login with token
    - passing invalid region
    - passing valid region (check .netrc file to see if the persisted region is the correct one)
- Login without token
    - passing invalid region
    - passing valid region (check .netrc file to see if the persisted region is the correct one)
- Pull Languages
- Pull Components
- Push Components
- Delete Component
- Delete Datasources
- Sync
- Generate Migration
- Run Migration
- Rollback migration

So, for example, to test the `login with token` scenario, you should, from the root of the project, run:

```sh
yarn install
node . login --token <YOUR_TOKEN> --region eu
```

I've tested each of them and everything seemed to be working nicely, but a second view is always more than welcomed.

## What is the new behavior?

[EXT-2186]: https://storyblok.atlassian.net/browse/EXT-2186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ademarCardoso — APPROVED** [review]
It's working very well, congratulations 🚀

**Comment by BibiSebi** [comment]
@ademarCardoso thank you for your quick review, it is very much appreciated especially given that you are most likely very busy at the moment. If you have the time, would you please share some information on how to publish a new version of the CLI or what the release flow is?

**Comment by demetriusfeijoo** [comment]
Hey @BibiSebi, it was released here: https://github.com/storyblok/storyblok-cli/releases/tag/v3.27.0

As soon as it got merged to the master branch, the `release workflow` was triggered. 
This workflow uses a package called `semantic-release` which handles all the processes to release a new version. It only requires the commits to use a `semantic versioning` approach (which I didn't do 🤣).

But yeah, it's released 🙌

**Comment by ademarCardoso** [comment]
> @ademarCardoso thank you for your quick review, it is very much appreciated especially given that you are most likely very busy at the moment. If you have the time, would you please share some information on how to publish a new version of the CLI or what the release flow is?

@BibiSebi  Ping me on slack and i can share all the things 😄 I Already talked with @demetriusfeijoo about that

**Pull request merged**
